### ISSUE TITLE
Tax applied to shipping even if "Tax Class for Shipping" is set to None

### ISSUE THREAD

**Issue by Peekmo** [taxjar/taxjar-magento-extension#39]
Hello,

I experience an issue with the tax calculation. It seems that the tax is applied to shipping cost as well, even if in "System > Configuration > Tax > Tax Classes > Tax Class for shipping" is set to none.

Regards,
Peekmo

**Comment by ryanreeves-taxjar** [comment]
Hi @Peekmo,

When calculating tax using the SmartCalcs api, we automatically determine if shipping should be taxable based on the shipping to and from locations. Shipping taxes vary from state to state, which is why we can't use a single rule to determine the rate. You can read more about taxing shipping on our blog post here: https://blog.taxjar.com/sales-tax-and-shipping/

When not using Smartcalcs, the "Tax class for shipping" setting is used. This includes the backup rates TaxJar syncs as well as Magento's native zip code based rates.

If there is anything else we can help with, please feel free to contact our support team at support@taxjar.com!
